### PR TITLE
load all models before execution

### PR DESCRIPTION
**Pull request by mamantoha**

### CODE REVIEW

**Comment by soulfly** [comment]
Hi @mamantoha, thanks for this PR! 
Would you like to provide more comments what issues do you have?

Also, models can be placed directly in '/app/models/*.rb', not only inside nested models dirs, so this also needs to be addressed.

**Comment by mamantoha** [comment]
Hi @soulfly 

I think the problem is in my config.

`config.autoload_paths` is set to `[ "lib"]`.
If I add `config.autoload_paths += Dir[Rails.root.join('app', 'models', '{**/}')]` everything works correctly.

But I don't want to preload all models on application start.

```
rails c
Loading development environment (Rails 4.2.7.1)
2.3.0 :001 > ActiveRecord::Base.descendants.size
 => 1
```

After:

```
ActiveRecord::Base.descendants.size
 => 76
```

**Comment by mamantoha** [comment]
Also, I found the handy method `eager_load`, which can be used simply like so:

```
Rails.application.eager_load!
ActiveRecord::Base.descendants.size
 => 76
```

**Comment by soulfly** [comment]
Ok I see, you are right

I have this line in my current project 
`config.autoload_paths += Dir[ Rails.root.join('app', 'models', 'concerns', '**/') ]`
that's why I do not see any issues

I like the way with **eager_load**, will see how to add it properly

**Comment by soulfly** [comment]
I made a commit https://github.com/soulfly/unique_validation_inspector/commit/84535003a6f60f0d05486e745f2dff5a72c2041a 

@mamantoha please try it and let me know

**Comment by mamantoha** [comment]
It works :) So I close this PR.

**Comment by soulfly** [comment]
Cool, thanks! 

will release it shortly

**Comment by soulfly** [comment]
0.1.3 has been pushed
https://rubygems.org/gems/unique_validation_inspector/versions/0.1.3

**Comment by mamantoha** [comment]
Cool, thanks!

**Pull request closed without merging**
