### PR TITLE
add scopes to column validation checking

### PR DESCRIPTION
**Pull request by mrdougwright**
I was having trouble getting the gem to detect indexes once added.

For example, after adding this index:
```
add_index :players, [:external_player_id, :game_id], unique: true
```

with this validation:
```
class Player
...
validates :external_player_id, uniqueness: { scope: :game_id }
```

I would still get:
```
Model 'Player':
[:external_player_id] (scope 'game_id'). Index exists: false.
```

So I forked and updated the validation check a bit and this worked for me.

### CODE REVIEW

**Comment by soulfly** [comment]
Thank you, @mrdougwright for reporting this!
I will review your PR and get back here

**Comment by soulfly** [comment]
Thank you, @mrdougwright for reporting this!
I will review your PR and get back here

**Comment by soulfly** [comment]
@mrdougwright  I found what's wrong with my code

it finds the following index: 
`add_index :players, [:game_id, :external_player_id], unique: true`

but it should look for:
`add_index :players, [:external_player_id, :game_id], unique: true`

**Comment by mrdougwright** [comment]
Sweet! But I think my code is breaking tests? 😄

**Comment by soulfly** [comment]
Yes, I'm fixing tests now

a quick question:

what is 'unique' here, what's the idea?
`ActiveRecord::Base.connection.indexes(table_name.to_sym).select{|i| i.unique }`

**Comment by mrdougwright** [comment]
I thought it might be prudent to only check column names for unique indexes.

**Comment by soulfly** [comment]
got it, great catch 👍 
I made another commit and fixed tests, so now all is green ;)

**Comment by soulfly** [comment]
New version has been pushed to rubygems
https://rubygems.org/gems/unique_validation_inspector/versions/0.3.0

Thanks for you help, @mrdougwright  🥇

**Comment by mrdougwright** [comment]
Thanks for a great gem!

**Pull request merged**
